services:
  beacon:
    image: beacon:dev
    build:
      context: .
      dockerfile: docker/Dockerfile

  beacon-scheduler:
    image: beacon:dev
    build:
      context: .
      dockerfile: docker/Dockerfile

  beacon-telegram:
    image: beacon:dev
    build:
      context: .
      dockerfile: docker/Dockerfile
