{{- if .Values.slack.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "beacon.fullname" . }}-slack
  labels:
    {{- include "beacon.labels" . | nindent 4 }}
    app.kubernetes.io/component: slack
spec:
  replicas: 1
  {{- with .Values.slack.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "beacon.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: slack
  template:
    metadata:
      annotations:
        {{- include "beacon.configChecksum" . | nindent 8 }}
        {{- include "beacon.customCAChecksum" . | nindent 8 }}
        {{- with .Values.slack.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "beacon.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: slack
        {{- with .Values.slack.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "beacon.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if include "beacon.customCAEnabled" . }}
      initContainers:
        {{- include "beacon.customCAInitContainer" . | nindent 8 }}
      {{- end }}
      containers:
        - name: slack
          image: {{ include "beacon.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: BEACON_CONFIG_FILE
              value: /etc/beacon/beacon.conf
            - name: BEACON_SERVICE
              value: slack
            - name: BEACON_RUN_MIGRATIONS
              value: "0"
            {{- include "beacon.customCAEnv" . | nindent 12 }}
            - name: PYTHONUNBUFFERED
              value: "1"
            {{- with .Values.slack.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.slack.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- include "beacon.volumeMounts" . | nindent 12 }}
      volumes:
        {{- include "beacon.volumes" . | nindent 8 }}
      {{- with .Values.slack.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.slack.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- else }}
      {{- if $.Values.persistence.enabled }}
      affinity:
        {{- include "beacon.dataWorkerAffinity" $ | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- with .Values.slack.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
