{{- if not .Values.existingConfigSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "beacon.configSecretName" . }}
  labels:
    {{- include "beacon.labels" . | nindent 4 }}
type: Opaque
stringData:
  beacon.conf: |
    {{- include "beacon.config" . | trim | nindent 4 }}
{{- end }}
